name: PR

on:
  pull_request:
    types: [opened, edited, synchronize]
  pull_request_target:
    types: [closed]

jobs:
  check-pr-title:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          
      - name: Check PR Title
        uses: amannn/action-semantic-pull-request@v5
        id: lint_pr_title
        with:
          scopes: 'build, ci, docs, feat, fix, refactor, style, test'

  delete-merged-branch:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    permissions:
      contents: write
    steps:
      - name: Delete Merged Branch
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.git.deleteRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'heads/${{ github.event.pull_request.head.ref }}'
            });
