name: Pull Request Automation

on:
    pull_request_target:
        types: [opened, edited, synchronize]

jobs:
    check-pr-title:
        runs-on: ubuntu-latest
        steps:
            - name: Check PR Title
              uses: amannn/action-semantic-pull-request@v5
              with:
                scopes: 'buid, ci, docs, feat, fix, refactor, style, test'

    label-pr:
        runs-on: ubuntu-latest
        steps:
            - name: Label Pull Request
              uses: actions/labeler@v4
              with: 
                repo-token: ${{ secrets.GH_TOKEN }}
                sync-labels: true